// Benign test-suite generator. Produces a `test/Benign.t.sol` automatically
// from the target source + Red's exploit report, then prunes tests that don't
// pass on the UNPATCHED bytecode.
//
// Contract with Blue:
//   - Generated tests MUST pass on the original (unpatched) fork. If they
//     don't, they're wrong benign fixtures, not regressions, and we drop
//     them before handing the suite to Blue.
//   - Blue will then require them to also pass on the PATCHED bytecode.
//     Any test that passes on unpatched but fails on patched is a
//     *real* regression and the patch must be rejected.
//
// Minimum contract: at least 3 surviving tests. Fewer means we don't have a
// credible regression harness and Blue can't run.

import type { ExploitReport } from "../reporter/format.js";
import { SandboxManager } from "../sandbox/manager.js";
import {
  chatCompletion,
  type ProviderConfig,
  type Message,
} from "../agent/provider.js";
import {
  subscriptionCompletion,
  mapToClaudeCliModel,
} from "../agent/provider-subscription.js";

export interface GenerateBenignArgs {
  sandbox: SandboxManager;
  /** Sandbox container id that already has the ORIGINAL project seeded. */
  sandboxId: string;
  originalSource: string;
  /** Name of the .sol file relative to project src/. */
  sourceFilename: string;
  exploitReport: ExploitReport;
  /** Project root in-container that builds the UNPATCHED contract. */
  originalProjectRoot: string;
  /** Path under each project where the benign suite should live. */
  benignTestPath: string;
  /** Fork block and RPC for the forge run. */
  forkBlockNumber: number;
  rpcUrl: string;
  /** Target contract address on the fork. */
  targetAddress: string;
  /** Contract name for Forge to build + extract. */
  contractName: string;
  /** Minimum tests that must survive pruning. */
  minTests?: number;
  /** Model provider override. If omitted, reads env. */
  provider?: ProviderConfig;
}

export interface GenerateBenignResult {
  /** Final compilable test/Benign.t.sol contents. */
  benignSource: string;
  /** Test names that survived (passed on unpatched). */
  survivingTests: string[];
  /** Test names generated by the model that were pruned (failed on unpatched). */
  prunedTests: string[];
  attempts: number;
}

const DEFAULT_MIN_TESTS = 3;

export async function generateBenign(
  args: GenerateBenignArgs
): Promise<GenerateBenignResult> {
  const minTests = args.minTests ?? DEFAULT_MIN_TESTS;

  // Two attempts max. Second attempt gets a sharpened prompt.
  let lastError = "";
  let generated = "";
  let survivors: string[] = [];
  let pruned: string[] = [];

  for (let attempt = 1; attempt <= 2; attempt++) {
    const sharpen = attempt === 2 ? lastError : undefined;
    try {
      generated = await llmGenerateBenign({
        originalSource: args.originalSource,
        exploitReport: args.exploitReport,
        contractName: args.contractName,
        targetAddress: args.targetAddress,
        sharpenHint: sharpen,
        provider: args.provider,
      });
    } catch (err: any) {
      lastError = `LLM generation failed: ${err?.message ?? err}`;
      continue;
    }

    // Prune tests that fail on the unpatched bytecode.
    const pruneResult = await pruneAgainstUnpatched({
      sandbox: args.sandbox,
      sandboxId: args.sandboxId,
      benignSource: generated,
      benignTestPath: args.benignTestPath,
      originalProjectRoot: args.originalProjectRoot,
      contractName: args.contractName,
      forkBlockNumber: args.forkBlockNumber,
      rpcUrl: args.rpcUrl,
    });

    survivors = pruneResult.survivors;
    pruned = pruneResult.pruned;
    generated = pruneResult.prunedSource;

    if (survivors.length >= minTests) {
      return {
        benignSource: generated,
        survivingTests: survivors,
        prunedTests: pruned,
        attempts: attempt,
      };
    }

    lastError = `Only ${survivors.length}/${minTests} tests survived pruning on the unpatched fork. Pruned: ${pruned.join(", ")}. Last forge output: ${pruneResult.lastRawOutput.slice(0, 1_500)}`;
  }

  throw new Error(
    `Benign suite generator failed after 2 attempts: ${lastError}\n\n` +
      `Blue cannot run without a credible regression harness. ` +
      `Last generated source (first 1KB):\n${generated.slice(0, 1_000)}`
  );
}

// ---------------------------------------------------------------------
// LLM call
// ---------------------------------------------------------------------

async function llmGenerateBenign(args: {
  originalSource: string;
  exploitReport: ExploitReport;
  contractName: string;
  targetAddress: string;
  sharpenHint?: string;
  provider?: ProviderConfig;
}): Promise<string> {
  const vuln = args.exploitReport.vulnerability;
  const sharpenSection = args.sharpenHint
    ? `\n\n## First attempt was rejected\n\nHere's what happened on attempt 1:\n\n${args.sharpenHint}\n\nMake the tests more robust: rely on zero-default state, avoid calling functions that may not exist on the original bytecode, and skip assertions about specific return values unless you can derive them from the source.\n`
    : "";

  const systemPrompt = `You generate Foundry benign happy-path tests for smart-contract vulnerability harnesses.

Your output will be compiled against the ORIGINAL (unpatched) contract, etched at a real mainnet address on a mainnet fork. Tests that pass here define the regression baseline that a later patch must preserve.

Rules:
- Output ONLY compilable Solidity — a single contract named \`BenignTest is Test\`, plus any fixture contracts (tokens, mock routers) it needs. No markdown fences, no explanation.
- Solidity pragma: \`pragma solidity ^0.8.17;\`.
- Import \`forge-std/Test.sol\` for the cheatcodes.
- Do NOT \`import\` from \`src/\` — define minimal interfaces inline, same way Red does in the exploit test.
- Use \`vm.envString("ETH_RPC_URL")\`, \`vm.envOr("DEXIBLE_FORK_BLOCK", uint256(<defaultBlock>))\`, and \`vm.envBytes("DEXIBLE_RUNTIME_BYTECODE")\` with \`vm.etch(TARGET, code)\` in setUp so the harness's bytecode swap works. The target address goes in a \`constant TARGET\` at the top of the test contract.
- Read \`vm.envOr("DEXIBLE_PATCHED", uint256(0)) == 1\` into an \`isPatched\` bool so the same file works on both variants. Tests that call patched-only selectors must early-return when \`!isPatched\`.
- Use cheatcodes: \`makeAddr\`, \`deal\`, \`prank\`, \`vm.expectRevert\` as needed.
- Prefer tests that assert ONLY that a call does not revert, counts incremented, or simple state changes. Don't assert exact return values you can't derive from the source.
- 5-8 tests total. Every test name starts with \`test\` (Foundry convention).

Target the vulnerable functions listed below — generate happy-path tests that exercise those same functions with benign inputs, so a later patch is forced to preserve legitimate use.`;

  const userPrompt = `## Target contract

**Name:** ${args.contractName}
**Address on fork:** ${args.targetAddress}
**Block:** ${args.exploitReport.blockNumber}

## Vulnerability (for context — do NOT exploit it in the benign tests)

- Class: ${vuln.class}
- Affected functions: ${vuln.functions.join(", ") || "(none specified)"}
- Description: ${vuln.description}

## Contract source

\`\`\`solidity
${args.originalSource.slice(0, 35_000)}
\`\`\`${sharpenSection}

## Output

Return ONLY the complete \`test/Benign.t.sol\` file contents. No markdown fences, no prose.`;

  const messages: Message[] = [
    { role: "system", content: systemPrompt },
    { role: "user", content: userPrompt },
  ];

  // Route: subscription (claude -p) if any of these are set:
  //   - BENIGN_VIA_CLAUDE_CLI=1  (explicit, highest priority)
  //   - BLUE_VIA_CLAUDE_CLI=1    (default for subscription-mode duels)
  //   - BLUE_VIA_SUBSCRIPTION=1  (legacy flag, kept for back-compat)
  // Otherwise the configured OpenRouter provider.
  const benignFlag = process.env.BENIGN_VIA_CLAUDE_CLI;
  const blueCliFlag = process.env.BLUE_VIA_CLAUDE_CLI;
  const legacyFlag = process.env.BLUE_VIA_SUBSCRIPTION;
  const viaSubscription =
    benignFlag === "1" ||
    benignFlag === "true" ||
    blueCliFlag === "1" ||
    blueCliFlag === "true" ||
    legacyFlag === "1" ||
    legacyFlag === "true";

  let text: string;
  if (viaSubscription) {
    // Use Opus 4.7 by default on the subscription path — consistent with
    // Blue's brain in runBlueTeamViaClaudeCli, and Sonnet's Solidity output
    // is noticeably weaker. Override via BENIGN_MODEL / STRATEGIC_MODEL.
    const modelAlias =
      process.env.BENIGN_MODEL ??
      process.env.STRATEGIC_MODEL ??
      "claude-opus-4-7";
    const model = mapToClaudeCliModel(modelAlias);
    // 5-minute timeout — Solidity test generation on a 35KB contract
    // routinely takes 2-3 minutes on Opus.
    const resp = await subscriptionCompletion(
      { model, timeoutMs: 300_000 },
      messages
    );
    text = resp.message.content ?? "";
  } else {
    const provider = args.provider ?? resolveDefaultProvider();
    const resp = await chatCompletion(provider, messages);
    text = resp.message.content ?? "";
  }

  return extractSolidity(text);
}

function resolveDefaultProvider(): ProviderConfig {
  const key = process.env.OPENROUTER_API_KEY;
  if (!key) {
    throw new Error(
      "No provider configured for benign generator. Set OPENROUTER_API_KEY " +
        "or pass `provider` explicitly, or set BLUE_VIA_SUBSCRIPTION=1 to use claude -p."
    );
  }
  return {
    provider: "openrouter",
    model: process.env.BLUE_BENIGN_MODEL ?? "anthropic/claude-sonnet-4-6",
    baseUrl: "https://openrouter.ai/api/v1",
    apiKey: key,
  };
}

// Extract Solidity source from an LLM response. Opus sometimes wraps the
// output in markdown fences and prepends explanatory prose even when told
// not to. Strategy:
//   1. If there's a ```solidity / ```sol / ``` fenced block, take the LAST
//      one (Opus usually puts the final answer last).
//   2. Else, find the first `// SPDX` or `pragma solidity` and slice from
//      there — drops any preamble.
//   3. Else, return the trimmed raw text.
function extractSolidity(text: string): string {
  if (!text) return "";

  // 1. Prefer the last fenced code block.
  const fenceRe = /```(?:solidity|sol)?\s*\n([\s\S]*?)```/gi;
  let lastFence: string | null = null;
  let m: RegExpExecArray | null;
  while ((m = fenceRe.exec(text)) !== null) {
    if (m[1]) lastFence = m[1];
  }
  if (lastFence) return stripPreamble(lastFence.trim());

  // 2. Slice from first SPDX/pragma marker.
  return stripPreamble(text.trim());
}

function stripPreamble(src: string): string {
  const spdxIdx = src.indexOf("// SPDX-License-Identifier");
  const pragmaIdx = src.indexOf("pragma solidity");
  const candidates = [spdxIdx, pragmaIdx].filter((i) => i >= 0);
  if (candidates.length === 0) return src;
  const cut = Math.min(...candidates);
  return cut > 0 ? src.slice(cut).trim() : src;
}

// ---------------------------------------------------------------------
// Pruning
// ---------------------------------------------------------------------

interface PruneArgs {
  sandbox: SandboxManager;
  sandboxId: string;
  benignSource: string;
  benignTestPath: string;
  originalProjectRoot: string;
  contractName: string;
  forkBlockNumber: number;
  rpcUrl: string;
}

interface PruneResult {
  survivors: string[];
  pruned: string[];
  prunedSource: string;
  lastRawOutput: string;
}

async function pruneAgainstUnpatched(args: PruneArgs): Promise<PruneResult> {
  // Write the generated source into the original project's test/ dir.
  const fullBenignPath = joinUnix(
    args.originalProjectRoot,
    args.benignTestPath
  );
  await args.sandbox.writeFile(
    args.sandboxId,
    fullBenignPath,
    args.benignSource
  );

  // Build the original so we can pull runtime bytecode for etching.
  const build = await args.sandbox.exec(
    args.sandboxId,
    `cd '${args.originalProjectRoot}' && forge build --extra-output storageLayout 2>&1`,
    180_000
  );
  if (build.exitCode !== 0) {
    return {
      survivors: [],
      pruned: [],
      prunedSource: args.benignSource,
      lastRawOutput: (build.stdout + "\n" + build.stderr).slice(-3_000),
    };
  }

  const artifactPath = `${args.originalProjectRoot}/out/${args.contractName}.sol/${args.contractName}.json`;
  const artifact = await args.sandbox.tryReadFile(args.sandboxId, artifactPath);
  if (!artifact) {
    return {
      survivors: [],
      pruned: [],
      prunedSource: args.benignSource,
      lastRawOutput: `Artifact not found: ${artifactPath}`,
    };
  }
  let runtimeBytecode = "";
  try {
    const parsed: any = JSON.parse(artifact);
    runtimeBytecode = parsed?.deployedBytecode?.object ?? "";
    if (runtimeBytecode && !runtimeBytecode.startsWith("0x")) {
      runtimeBytecode = `0x${runtimeBytecode}`;
    }
  } catch (e) {
    return {
      survivors: [],
      pruned: [],
      prunedSource: args.benignSource,
      lastRawOutput: `Artifact parse error: ${(e as Error).message}`,
    };
  }

  const envPrefix = [
    `ETH_RPC_URL='${args.rpcUrl.replace(/'/g, "'\\''")}'`,
    `DEXIBLE_FORK_BLOCK='${args.forkBlockNumber}'`,
    `DEXIBLE_RUNTIME_BYTECODE='${runtimeBytecode}'`,
    // Deliberately omit DEXIBLE_PATCHED so isPatched=false in the benign tests.
  ].join(" ");

  const cmd = `cd '${args.originalProjectRoot}' && ${envPrefix} forge test --match-path '${args.benignTestPath}' -vv --json 2>/tmp/forge.err; echo "__exit:$?"`;
  const run = await args.sandbox.exec(args.sandboxId, cmd, 600_000);
  const rawOutput = run.stdout + "\n----stderr----\n" + run.stderr;

  const parsedForge = tryParseForgeJson(run.stdout);
  const survivors: string[] = [];
  const pruned: string[] = [];
  if (parsedForge) {
    for (const contractKey of Object.keys(parsedForge)) {
      const contract: any = parsedForge[contractKey];
      if (!contract?.test_results) continue;
      for (const [name, tr] of Object.entries<any>(contract.test_results)) {
        const shortName = name.replace(/\(.*\)$/, "");
        if (tr?.status === "Success") survivors.push(shortName);
        else pruned.push(shortName);
      }
    }
  }

  // If at least one test survived, rewrite the source to contain ONLY
  // surviving tests so Blue doesn't have to dodge red herrings.
  let prunedSource = args.benignSource;
  if (pruned.length > 0 && survivors.length > 0) {
    prunedSource = stripFailingTests(args.benignSource, pruned);
    // Re-write the pruned source back so subsequent runs see it.
    await args.sandbox.writeFile(
      args.sandboxId,
      fullBenignPath,
      prunedSource
    );
  }

  return {
    survivors,
    pruned,
    prunedSource,
    lastRawOutput: rawOutput,
  };
}

// Remove `function <testName>(...) {...}` blocks whose base name is in the
// failing set. Keeps the rest of the file intact.
function stripFailingTests(source: string, failingNames: string[]): string {
  let result = source;
  for (const name of failingNames) {
    result = removeFunctionBlock(result, name);
  }
  return result;
}

function removeFunctionBlock(source: string, funcName: string): string {
  const startRe = new RegExp(
    `(\\n\\s*/\\*\\*[\\s\\S]*?\\*/)?\\s*function\\s+${escapeRegex(funcName)}\\s*\\(`,
    "m"
  );
  const match = source.match(startRe);
  if (!match) return source;
  const start = match.index ?? 0;
  // Find the opening brace of the function body.
  const braceIdx = source.indexOf("{", start);
  if (braceIdx < 0) return source;
  let depth = 1;
  let i = braceIdx + 1;
  while (i < source.length && depth > 0) {
    const ch = source[i];
    if (ch === "{") depth++;
    else if (ch === "}") depth--;
    i++;
  }
  if (depth !== 0) return source;
  return source.slice(0, start) + source.slice(i);
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function tryParseForgeJson(stdout: string): Record<string, unknown> | null {
  const start = stdout.indexOf("{");
  if (start < 0) return null;
  try {
    return JSON.parse(stdout.slice(start)) as Record<string, unknown>;
  } catch {
    const end = stdout.lastIndexOf("}");
    if (end <= start) return null;
    try {
      return JSON.parse(stdout.slice(start, end + 1)) as Record<string, unknown>;
    } catch {
      return null;
    }
  }
}

function joinUnix(...parts: string[]): string {
  return parts
    .map((p) => p.replace(/\\/g, "/").replace(/\/+$/, ""))
    .join("/")
    .replace(/\/+/g, "/");
}
