// Historic-patch differ.
//
// Given Blue's patch and the historic patch (from fetcher.ts), produce a
// PatchComparison that the demo UI + defensibility report consume.
//
// Line-level diff via the `diff` npm package. Function-level comparison is a
// simple regex-based touched-function extraction — good enough for Solidity
// and honest about its limits (we're not running a full parser).
//
// The `summary` field is generated by `claude -p` on the Max subscription
// (model claude-opus-4-7). Subscription = $0.

import { structuredPatch } from "diff";

import type { HistoricPatch } from "./fetcher.js";
import {
  subscriptionCompletion,
  type SubscriptionConfig,
} from "../agent/provider-subscription.js";

export interface PatchComparison {
  contractName: string;
  bluePatch: {
    source: string;
    addedLines: number;
    removedLines: number;
    approach: string;
  };
  historicPatch: {
    source?: string;
    addedLines?: number;
    removedLines?: number;
    approach?: string;
    available: boolean;
  };
  comparison: {
    sameFunctionTargeted: boolean;
    similarApproach: boolean;
    blueSimpler: boolean;
    blueNovel: boolean;
    summary: string;
  };
}

// Count +/- lines in the unified diff hunks produced by `diff.structuredPatch`.
function countDiff(oldStr: string, newStr: string): { added: number; removed: number } {
  const patch = structuredPatch("old", "new", oldStr, newStr, "", "", { context: 0 });
  let added = 0;
  let removed = 0;
  for (const hunk of patch.hunks) {
    for (const line of hunk.lines) {
      if (line.startsWith("+")) added++;
      else if (line.startsWith("-")) removed++;
    }
  }
  return { added, removed };
}

// Best-effort Solidity function-name extraction. Matches:
//   function foo(...) ... { ... }
// Returns a Set of function names that appear as `function <name>(` in the text.
export function extractFunctionNames(solidity: string): Set<string> {
  const names = new Set<string>();
  const re = /\bfunction\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*\(/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(solidity)) !== null) {
    names.add(m[1]);
  }
  return names;
}

// Return the set of function names whose definitions DIFFER between the two
// sources. Heuristic: a function is "touched" if its name appears in one side
// but not the other, OR if any line mentioning `function <name>` differs.
function touchedFunctions(oldStr: string, newStr: string): Set<string> {
  const touched = new Set<string>();
  const oldFns = extractFunctionNames(oldStr);
  const newFns = extractFunctionNames(newStr);
  for (const n of oldFns) if (!newFns.has(n)) touched.add(n);
  for (const n of newFns) if (!oldFns.has(n)) touched.add(n);

  // Also grab functions whose bodies differ in the line diff.
  const patch = structuredPatch("old", "new", oldStr, newStr, "", "", { context: 3 });
  for (const hunk of patch.hunks) {
    for (const line of hunk.lines) {
      const m = line.match(/\bfunction\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*\(/);
      if (m) touched.add(m[1]);
    }
  }
  return touched;
}

// Short one-phrase "approach" label inferred from what the diff added.
// Heuristic only — used as a cheap fallback if the LLM summary fails.
function inferApproach(original: string, patched: string): string {
  const patch = structuredPatch("old", "new", original, patched, "", "", { context: 1 });
  const added: string[] = [];
  for (const hunk of patch.hunks) {
    for (const line of hunk.lines) if (line.startsWith("+")) added.push(line.slice(1));
  }
  const joined = added.join("\n").toLowerCase();
  const signals: string[] = [];
  if (/require\s*\(/.test(joined)) signals.push("require() checks");
  if (/mapping\s*\(\s*address\s*=>\s*bool\s*\)/.test(joined)) signals.push("allowlist mapping");
  if (/onlyadmin|onlyowner|only[a-z]+/i.test(joined)) signals.push("role-gated modifier");
  if (/revert\s+[a-z]/i.test(joined)) signals.push("custom revert");
  if (/if\s*\(!.*\)\s*revert/.test(joined)) signals.push("guard clause");
  if (/approve\s*\(/.test(joined)) signals.push("approval handling");
  if (/pause|paused/i.test(joined)) signals.push("pause circuit");
  return signals.length ? signals.join(" + ") : "(no pattern signals detected)";
}

// Ask Opus 4.7 (Max subscription) for a 2-3 sentence grounded comparison.
async function llmSummary(args: {
  contractName: string;
  originalSource: string;
  bluePatch: string;
  historicPatch: HistoricPatch;
}): Promise<string> {
  const { contractName, originalSource, bluePatch, historicPatch } = args;
  const historicBlock = historicPatch.patchedSource
    ? `HISTORIC PATCH SOURCE (${historicPatch.source}, ${historicPatch.sourceUrl}):\n\`\`\`solidity\n${historicPatch.patchedSource}\n\`\`\``
    : historicPatch.patchedFunction
      ? `HISTORIC PATCH FUNCTION (${historicPatch.source}, ${historicPatch.sourceUrl}):\n\`\`\`solidity\n${historicPatch.patchedFunction}\n\`\`\``
      : `HISTORIC PATCH: unavailable. Source URL: ${historicPatch.sourceUrl}. Notes: ${historicPatch.notes ?? "none"}.`;

  const system =
    "You are comparing two defensive patches for a real DeFi exploit. " +
    "You MUST be grounded in the code provided — do not speculate about code you cannot see. " +
    "Output 2-3 plain sentences, no markdown, no preamble. Mention the targeted function by name " +
    "if identifiable. If the historic patch is unavailable, say so plainly and describe only Blue's.";

  const user =
    `Contract: ${contractName}\n\n` +
    `ORIGINAL (vulnerable) SOURCE:\n\`\`\`solidity\n${originalSource}\n\`\`\`\n\n` +
    `BLUE'S PATCH:\n\`\`\`solidity\n${bluePatch}\n\`\`\`\n\n` +
    `${historicBlock}\n\n` +
    `Write a grounded 2-3 sentence comparison of Blue's approach vs what the protocol actually shipped.`;

  const config: SubscriptionConfig = {
    model: "claude-opus-4-7",
    timeoutMs: 180_000,
  };

  try {
    const resp = await subscriptionCompletion(config, [
      { role: "system", content: system },
      { role: "user", content: user },
    ]);
    const text =
      typeof resp.message.content === "string"
        ? resp.message.content
        : JSON.stringify(resp.message.content);
    return text.trim().slice(0, 1200);
  } catch (e) {
    return `LLM summary unavailable (${(e as Error).message.slice(0, 80)}). Blue's approach: ${inferApproach(originalSource, bluePatch)}.`;
  }
}

export async function compareToHistoric(args: {
  contractName: string;
  originalSource: string;
  bluePatch: string;
  historicPatch: HistoricPatch;
}): Promise<PatchComparison> {
  const { contractName, originalSource, bluePatch, historicPatch } = args;

  const blueCounts = countDiff(originalSource, bluePatch);
  const blueApproach = inferApproach(originalSource, bluePatch);
  const blueTouched = touchedFunctions(originalSource, bluePatch);

  let historicAvailable = false;
  let historicCounts: { added: number; removed: number } | null = null;
  let historicApproach: string | undefined;
  let historicTouched: Set<string> = new Set();

  if (historicPatch.source !== "unavailable" && historicPatch.patchedSource) {
    historicAvailable = true;
    historicCounts = countDiff(originalSource, historicPatch.patchedSource);
    historicApproach = inferApproach(originalSource, historicPatch.patchedSource);
    historicTouched = touchedFunctions(originalSource, historicPatch.patchedSource);
  } else if (historicPatch.source !== "unavailable" && historicPatch.patchedFunction) {
    // Have a function snippet but not full source — mark available with caveats.
    historicAvailable = true;
    historicApproach = inferApproach("", historicPatch.patchedFunction);
    historicTouched = extractFunctionNames(historicPatch.patchedFunction);
  }

  // Function-level overlap
  const overlap = new Set<string>();
  for (const f of blueTouched) if (historicTouched.has(f)) overlap.add(f);
  const sameFunctionTargeted = overlap.size > 0;

  // Approach similarity: cheap token overlap between approach strings.
  let similarApproach = false;
  if (historicApproach) {
    const aTokens = new Set(blueApproach.split(/\W+/).filter((t) => t.length > 3));
    const bTokens = new Set(historicApproach.split(/\W+/).filter((t) => t.length > 3));
    let shared = 0;
    for (const t of aTokens) if (bTokens.has(t)) shared++;
    similarApproach = shared >= 2;
  }

  // Simpler = strictly fewer net-added lines (added - removed)
  const blueNet = blueCounts.added - blueCounts.removed;
  const historicNet =
    historicCounts != null ? historicCounts.added - historicCounts.removed : null;
  const blueSimpler = historicNet != null ? blueNet < historicNet : false;

  // Novel = overlap exists BUT approaches disagree (different tactic on the
  // same function). If we have no historic approach string we cannot claim novelty.
  const blueNovel =
    sameFunctionTargeted && historicApproach != null && !similarApproach;

  const summary = await llmSummary({ contractName, originalSource, bluePatch, historicPatch });

  return {
    contractName,
    bluePatch: {
      source: bluePatch,
      addedLines: blueCounts.added,
      removedLines: blueCounts.removed,
      approach: blueApproach,
    },
    historicPatch: {
      source: historicPatch.patchedSource,
      addedLines: historicCounts?.added,
      removedLines: historicCounts?.removed,
      approach: historicApproach,
      available: historicAvailable,
    },
    comparison: {
      sameFunctionTargeted,
      similarApproach,
      blueSimpler,
      blueNovel,
      summary,
    },
  };
}
